/*
	Warning! All the contents are automatically generated by KakennL which might be not correct!
   ▄▄▄▄▄▄▄  ▄  ▄         ▄▄▄▄▄▄▄  
   █ ▄▄▄ █ ▄▄█▀█ ▄▀▀▀▄▀▀ █ ▄▄▄ █  
   █ ███ █  ▀█▀ ▄██▀▄█▀  █ ███ █  
   █▄▄▄▄▄█ ▄▀▄ ▄ █▀▄ ▄▀█ █▄▄▄▄▄█  
   ▄▄▄ ▄▄▄▄█▀█▄▀█▄███ ▄█▄▄   ▄    
   ██▄▀▄█▄▀▀▄▀▀ ▀█▀▀▄   ▀█▄▄▀▄▄█  
      █  ▄▄▄  ▀▄█ █ ▀▀██▄█  ▄ █▄  
   ▀ █▄▀ ▄█▀█▄██▀▀ ▄▀█ ▀▀▀▄ █ ▄█  
   ▄ ▄▄█▄▄ ▄▀▀▄▀█▀█▄█ ▄██▄▄ █ █▄  
   ▄▀███ ▄▄ ▄▀▀ █▀▀█ ▄ ▀▀█  ▀▀▄█  
   ▄▀▀██▄▄ █▀▄▀▄█▄ ▀▀  ▄▄▄▄█▀ ▀   
   ▄▄▄▄▄▄▄ █  ███▀ ▀▀███ ▄ █▄▀██  
   █ ▄▄▄ █ █  ▄█▀▀▄██▀ █▄▄▄█▀ █   
   █ ███ █ ▄▀▄▀   ▀█▀ █▀▄ ▀█▄▀▀█  
   █▄▄▄▄▄█ █▀▀ ▄█▀ ▄▀ ▀█ ▄▄▄▄ █▄  
                                  
*/
#include <stdio.h>

int main(void)
{
    // 各类水果的单价（元/千克）
    double price_apple = 3.2;
    double price_pear = 1.96;
    double price_banana = 3.0;
    double price_cherry = 24.0;

    // 顾客购买的水果数量（斤）
    double num_apple = 1.5;
    double num_pear = 2.0;
    double num_banana = 3.0;
    double num_cherry = 1.5;

    // 顾客所付款项（元）
    double payment = 100.0;

    // 计算顾客购买各类水果的重量（千克）和应付价钱（元）
    double weight_apple = num_apple * 1000; // 1斤 = 1000克
    double weight_pear = num_pear * 1000;
    double weight_banana = num_banana * 1000;
    double weight_cherry = num_cherry * 1000;
    double cost_apple = weight_apple * price_apple;
    double cost_pear = weight_pear * price_pear;
    double cost_banana = weight_banana * price_banana;
    double cost_cherry = weight_cherry * price_cherry;
    double total_cost = cost_apple + cost_pear + cost_banana + cost_cherry; // 总价格

    // 输出顾客购买各类水果的名称，对应的重量和应付价钱
    printf("Apple: %.2f kg, cost %.2f yuan\n", weight_apple, cost_apple);
    printf("Pear: %.2f kg, cost %.2f yuan\n", weight_pear, cost_pear);
    printf("Banana: %.2f kg, cost %.2f yuan\n", weight_banana, cost_banana);
    printf("Cherry: %.2f kg, cost %.2f yuan\n", weight_cherry, cost_cherry);

    // 显示顾客所付款项，输出应找回的款项
    printf("Payment: %.2f yuan\n", payment);
    printf("Change: %.2f yuan\n", payment - total_cost);

    return 0;
}
