/*
	Warning! All the contents are automatically generated by KakennL which might be not correct!
   ▄▄▄▄▄▄▄  ▄  ▄         ▄▄▄▄▄▄▄  
   █ ▄▄▄ █ ▄▄█▀█ ▄▀▀▀▄▀▀ █ ▄▄▄ █  
   █ ███ █  ▀█▀ ▄██▀▄█▀  █ ███ █  
   █▄▄▄▄▄█ ▄▀▄ ▄ █▀▄ ▄▀█ █▄▄▄▄▄█  
   ▄▄▄ ▄▄▄▄█▀█▄▀█▄███ ▄█▄▄   ▄    
   ██▄▀▄█▄▀▀▄▀▀ ▀█▀▀▄   ▀█▄▄▀▄▄█  
      █  ▄▄▄  ▀▄█ █ ▀▀██▄█  ▄ █▄  
   ▀ █▄▀ ▄█▀█▄██▀▀ ▄▀█ ▀▀▀▄ █ ▄█  
   ▄ ▄▄█▄▄ ▄▀▀▄▀█▀█▄█ ▄██▄▄ █ █▄  
   ▄▀███ ▄▄ ▄▀▀ █▀▀█ ▄ ▀▀█  ▀▀▄█  
   ▄▀▀██▄▄ █▀▄▀▄█▄ ▀▀  ▄▄▄▄█▀ ▀   
   ▄▄▄▄▄▄▄ █  ███▀ ▀▀███ ▄ █▄▀██  
   █ ▄▄▄ █ █  ▄█▀▀▄██▀ █▄▄▄█▀ █   
   █ ███ █ ▄▀▄▀   ▀█▀ █▀▄ ▀█▄▀▀█  
   █▄▄▄▄▄█ █▀▀ ▄█▀ ▄▀ ▀█ ▄▄▄▄ █▄  
                                  
*/
#include <stdio.h>

int main(void)
{
    char str[100]; // 字符串
    int count_A = 0; // A字母出现的次数
    int count_B = 0; // B字母出现的次数
    int count_C = 0; // C字母出现的次数
    int count_D = 0; // D字母出现的次数
    int i; // 循环计数器

    printf("Enter a string:\n");
    scanf("%s", str); // 从键盘输入字符串

    printf("The original string is: %s\n", str); // 输出原始字符串

    // 统计A,B,C,D字母出现的次数
    for (i = 0; str[i] != '\0'; i++)
    {
        if (str[i] == 'A')
        {
            count_A++;
        }
        else if (str[i] == 'B')
        {
            count_B++;
        }
        else if (str[i] == 'C')
        {
            count_C++;
        }
        else if (str[i] == 'D')
        {
            count_D++;
        }
    }

    printf("The count of A is: %d\n", count_A); // 输出A字母出现的次数
    printf("The count of B is: %d\n", count_B); // 输出B字母出现的次数
    printf("The count of C is: %d\n", count_C); // 输出C字母出现的次数
    printf("The count of D is: %d\n", count_D); // 输出D字母出现的次数

    return 0;
}
