/*
	Warning! All the contents are automatically generated by KakennL which might be not correct!
   ▄▄▄▄▄▄▄  ▄  ▄         ▄▄▄▄▄▄▄  
   █ ▄▄▄ █ ▄▄█▀█ ▄▀▀▀▄▀▀ █ ▄▄▄ █  
   █ ███ █  ▀█▀ ▄██▀▄█▀  █ ███ █  
   █▄▄▄▄▄█ ▄▀▄ ▄ █▀▄ ▄▀█ █▄▄▄▄▄█  
   ▄▄▄ ▄▄▄▄█▀█▄▀█▄███ ▄█▄▄   ▄    
   ██▄▀▄█▄▀▀▄▀▀ ▀█▀▀▄   ▀█▄▄▀▄▄█  
      █  ▄▄▄  ▀▄█ █ ▀▀██▄█  ▄ █▄  
   ▀ █▄▀ ▄█▀█▄██▀▀ ▄▀█ ▀▀▀▄ █ ▄█  
   ▄ ▄▄█▄▄ ▄▀▀▄▀█▀█▄█ ▄██▄▄ █ █▄  
   ▄▀███ ▄▄ ▄▀▀ █▀▀█ ▄ ▀▀█  ▀▀▄█  
   ▄▀▀██▄▄ █▀▄▀▄█▄ ▀▀  ▄▄▄▄█▀ ▀   
   ▄▄▄▄▄▄▄ █  ███▀ ▀▀███ ▄ █▄▀██  
   █ ▄▄▄ █ █  ▄█▀▀▄██▀ █▄▄▄█▀ █   
   █ ███ █ ▄▀▄▀   ▀█▀ █▀▄ ▀█▄▀▀█  
   █▄▄▄▄▄█ █▀▀ ▄█▀ ▄▀ ▀█ ▄▄▄▄ █▄  
                                  
*/
#include <stdio.h>

int main(void)
{
    double principal; // 本金
    int term; // 存款期限（单位：月）
    double rate; // 利率
    double interest; // 到期利息
    double tax; // 到期利息税
    double total; // 到期本金及利息之和

    printf("Enter principal and term (in months):\n");
    scanf("%lf%d", &principal, &term);

    if (term == 6) // 如果期限是6个月，则利率为3.30%
    {
        rate = 0.033;
    }
    else if (term == 12) // 如果期限是12个月，则利率为3.50%
    {
        rate = 0.035;
    }
    else if (term == 24) // 如果期限是24个月，则利率为4.40%
    {
        rate = 0.044;
    }
    else if (term == 36) // 如果期限是36个月，则利率为5.00%
    {
        rate = 0.05;
    }
    else if (term == 60) // 如果期限是60个月，则利率为5.50%
    {
        rate = 0.055;
    }
    else // 如果期限不满足上述条件，则输出错误信息并退出
    {
        printf("Invalid term.\n");
        return 1;
    }

    interest = principal * rate * term / 12; // 计算到期利息
    tax = interest * 0.05; // 计算到期利息税
    total = principal + interest - tax; // 计算到期本金及利息之和

    printf("Interest: %.2lf\n", interest); // 输出到期利息
    printf("Principal and interest: %.2lf\n", total); // 输出到期本金及利息之和

    return 0;
}
